### ISSUE TITLE
Adding new Hosts via Excel not working

### ISSUE THREAD

**Issue by multimill** [k4yt3x/wg-meshconf#24] opened 2021-06-08 20:19 UTC
Hello,

I tried to add new hosts after some time and the program fails everytime with error "The value of Address cannot be automatically generated".

Steps to reproduce:

1. Create .csv file via "wg-meshconf init"
2. Open .csv file and add hosts
3. Use command "wg-meshconf init" -> everything works fine and missing data is added automatically
4. Open .csv file with Excel again and add a new host with only Name, Address and Endpoint and save it
5. Use command "wg-meshconf init" -> Error message  "The value of Address cannot be automatically generated" appears.

Is there any workaround for this except adding all hosts at the beginning? 

Thanks

**Comment by k4yt3x** [comment] 2021-06-11 01:12
wg-meshconf was designed to accept new hosts at any point. If you encountered this issue as described, then you've either found a bug or didn't do it right. I didn't manage to reproduce this error at my end.

I took my test file and added a new line:

![image](https://user-images.githubusercontent.com/21986859/121616202-71b72100-ca30-11eb-9341-ffcdf4ee25cf.png)

Then I ran init again:

![image](https://user-images.githubusercontent.com/21986859/121616135-4af8ea80-ca30-11eb-9d4b-97f5b49e050b.png)

Everything works as expected. Judging by the error message you're getting, are you sure you filled in `Address` correctly and saved it to file?

**Comment by multimill** [comment] 2021-06-11 19:46
I just tried again and I do have the same problem again. I am using the latest version of wg-meshconf on a Win10 machine. Running in normal cmd window.

I cannot upload .csv files here but I zipped them and uploaded them.

[examples.zip](https://github.com/k4yt3x/wg-meshconf/files/6640670/examples.zip)

So, the v1 is the file I get when I create a new .csv file via "wg-meshconf init" and put in 2 new lines with two servers. After running "wg-meshconf init" again I get the v2. So I do paste the new Server3 below the new created lines and save it like the v3 file. When I try to run the init command again I do get the given error.

Hope this helps to show my problem. Maybe I am missing something or enter the wrong values?!

**Comment by k4yt3x** [comment] 2021-06-12 03:49
> Okay, my problem is that in my config there is always an empty line created between the ones with vaules.

I see that in your CSV file. To wg-meshconf, it's a peer with all fields left empty.

> Maybe this does only happen on Windows 10?

I'm not sure if it's editor-specific. What editor are you using? Excel?

**Comment by multimill** [comment] 2021-06-12 14:20
> I'm not sure if it's editor-specific. What editor are you using? Excel?

I tried with different editors. First I used Excel but same does happen in LibreOffice Calc, Notepad++ or the normal notepad.exe from Windows. 
I just tried the same file on the Windows and Ubuntu machine (like the v1 I uploaded earlier) and on Ubuntu everything is fine while on Windows the empty lines are created.

Guess I will just stick with using it on Ubuntu and mount the .csv file on Windows to edit them.

**Comment by k4yt3x** [comment] 2021-06-12 15:28
I think I know what's going on: https://stackoverflow.com/questions/3348460/csv-file-written-with-python-has-blank-lines-between-each-row

**Comment by multimill** [comment] 2021-06-12 19:13
Yes, this does look like my problem. But I don't have any clue how to implement a fix.

**Comment by k4yt3x** [comment] 2021-06-12 21:11
Here's a quick & dirty way:

[wg-meshconf.zip](https://github.com/k4yt3x/wg-meshconf/files/6642894/wg-meshconf.zip)

This is a version in development. You'll need to do `pip install --user rich` before you can use it since this dependency is not included in the current release of wg-meshconf. Open a terminal and cd into the decompressed wg-meshconf folder. Instead of running `wg-meshconf` directly, do `python -m wg_meshconf` instad.

**Comment by multimill** [comment] 2021-06-14 20:11
Sorry for late reply but I could not manage to make it work. Do I just need to download that .zip, extract and run the wg_meshconf.py inside it? Tried it and got this:

```
C:\Users\multi\Desktop\wg-meshconf_neu\wg-meshconf\wg_meshconf>python -m wg_meshconf
Traceback (most recent call last):
  File "C:\Users\multi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\multi\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\multi\Desktop\wg-meshconf_neu\wg-meshconf\wg_meshconf\wg_meshconf.py", line 15, in <module>
    from .database_manager import DatabaseManager
ImportError: attempted relative import with no known parent package
```

**Comment by k4yt3x** [comment] 2021-06-14 21:50
You cannot run the python file directly. You'll need to run the wg_meshconf directory as a Python package. At the root directory of the package, do `python -m wg_meshconf`.

**Comment by multimill** [comment] 2021-06-15 15:09
Ahh I see. Thanks, I was in the wrong folder (the sub folder blow the setup.py). 

It's working now.

**Comment by k4yt3x** [comment] 2021-06-15 16:29
Meaning that the bug is no more?

**Comment by multimill** [comment] 2021-06-15 16:36
Yes, it's working as intended now. No more empty lines.

**Comment by k4yt3x** [comment] 2021-06-16 06:54
Great. I'll close this issue once I release the patch. Thanks for helping out with the debugging process.

**Closed** 2021-06-22 07:31 UTC
